FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

# Скачиваем зависимости (кешируем этот шаг для ускорения последующих сборок)
RUN mvn dependency:go-offline -B

RUN mvn clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "target/JWTSecuritySpring-0.0.1-SNAPSHOT.jar"]