services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_7password
      POSTGRES_DB: jwt_sec_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jwt_sec_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test_7password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - backend-network

  frontend:
    build:
      context: ./_frontend
      dockerfile: Dockerfile_frontend
    container_name: nginx_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge